# Generated by Django 3.1.7 on 2021-03-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210301_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='aritist',
            new_name='artist',
        ),
    ]
