# Generated by Django 3.1.7 on 2021-03-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210301_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
