# Generated by Django 3.1.7 on 2021-03-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210301_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Band',
            new_name='band',
        ),
    ]
