# Generated by Django 3.1.7 on 2021-03-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210301_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='band',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='album',
        ),
    ]
