# Generated by Django 3.1.7 on 2021-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210301_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='album_names',
            field=models.ManyToManyField(to='core.Album_title'),
        ),
    ]
