# Generated by Django 3.1.7 on 2021-03-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210301_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='album_names',
        ),
        migrations.DeleteModel(
            name='Album_title',
        ),
    ]
