# Generated by Django 3.1.7 on 2021-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210301_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='year_began',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
